{% set name = "pyload-ng" %}
{% set version = "0.5.0b3.dev95" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1125702e6cc98204dae1a3cd579ea9fb8bb9015f92633693bb4d35d0fa381fdd

build:
  entry_points:
    - pyload = pyload.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  skip: true  # [ppc64le]
#mini-racer on ppc64le isn't avalaible for now
requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - babel
    - jinja2
    - _osx >=26  # [osx]
  host:
    - pip
    - python
    - setuptools >=38.3
    - wheel
    - packaging
    - _osx >=26  # [osx]
  run:
    - python
    - aia-chaser >=0.9.0
    - cheroot
    - flask
    - flask-babel
    - flask-caching >=1.9,<2.dev0
    - flask-compress >=1.8,<2.dev0
    - flask-session
    - flask-themes2 >=1.0,<2.dev0
    - flask-wtf
    - bitmath >=1.3,<2.dev0
    - cryptography >=35.0.0
    - defusedxml
    - filetype >=1.0,<2.dev0
    - mini-racer
    - packaging
    - pycurl
    - pydantic
    - certifi
    - semver >=2.10,<3.dev0
    - setuptools >=38.3
    - _osx >=10  # [osx]

test:
  imports:
    - pyload
  commands:
    - set PYTHONIOENCODING=utf-8  # [win]
    - pip check
    - pyload --help
    - pyload --version
  requires:
    - pip

about:
  home: https://pyload.net
  summary: The free and open-source Download Manager written in pure Python
  license: AGPL-3.0-or-later
  license_file: LICENSE.md
  dev_url: https://github.com/pyload/pyload
  doc_url: https://github.com/pyload/pyload/wiki
  description: |
    *pyLoad* is a free and open source downloader for 1-click-hosting sites.
    It supports link decryption as well as all important container formats.
    Targeted for headless NASs it is designed to be extremely lightweight,
    fully customizable and remotely manageable via web interface.

extra:
  recipe-maintainers:
    - HeavyTony2
