{% set name = "pyload-ng" %}
{% set version = "0.5.0b3.dev92" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6236fd4adab415a5df6aff054fa18f7f67323c647d367e95830754e27897d126

build:
  entry_points:
    - pyload = pyload.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - babel
    - jinja2
  host:
    - pip
    - python
    - setuptools >=38.3
    - wheel
    - packaging
  run:
    - python
    - pip
    - cheroot
    - flask
    - flask-babel
    - flask-caching >=1.9,<2.dev0
    - flask-compress >=1.8,<2.dev0
    - flask-session
    - flask-themes2 >=1.0,<2.dev0
    - bitmath >=1.3,<2.dev0
    - cryptography >=35.0.0
    - filetype >=1.0,<2.dev0
    - pycurl
    - certifi
    - semver >=2.10,<3.dev0
    - setuptools >=38.3
    - packaging
    - cryptography
    - pydantic >=2.10.6,<2.11.dev0
    - mini-racer
    - msgspec >=0.18.6

test:
  imports:
    - pyload
  commands:
    - set PYTHONIOENCODING=utf-8  # [win]
    - pip check
    - pyload --help
    - pyload --version
  requires:
    - pip
    - msgspec =0.18.6 #odd version issue

about:
  home: https://pyload.net
  summary: The free and open-source Download Manager written in pure Python
  license: AGPL-3.0-or-later
  license_file: LICENSE.md
  dev_url: https://github.com/pyload/pyload
  doc_url: https://github.com/pyload/pyload/wiki
  description: |
    *pyLoad* is a free and open source downloader for 1-click-hosting sites.
    It supports link decryption as well as all important container formats.
    Targeted for headless NASs it is designed to be extremely lightweight,
    fully customizable and remotely manageable via web interface.

extra:
  recipe-maintainers:
    - HeavyTony2
