{% set name = "pyload-ng" %}
{% set version = "0.5.0b3.dev85" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 28ba5f879dc92aa7b49192dc4350b87d714561e3b9a4f8626bd7d1c56b1b2076

build:
  entry_points:
    - pyload = pyload.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python
    - setuptools >=38.3
    - wheel
  run:
    - python
    - cheroot >=8.4,<9.dev0
    - flask
    - flask-babel >=1.0,<2.dev0
    - flask-caching >=1.9,<2.dev0
    - flask-compress >=1.8,<2.dev0
    - flask-session >=0.4.1,<0.5.dev0  #Should be for 37 or less according to grayskull, but not according to the tests
    - flask-themes2 >=1.0,<2.dev0
    - bitmath >=1.3,<2.dev0
    - cryptography >=35.0.0,<40.0.0  # [python_impl == 'pypy']
    - cryptography >=35.0.0  # [python_impl == 'cpython']
    - brotlicffi  # [python_impl == 'pypy'] #required by flask-compress 1.14
    - filetype >=1.0,<2.dev0
    - js2py >=0.7,<1.dev0  # [py<312]
    - dukpy >=0.3.1  # [py>=312]
    - pycurl >=7.43,<8.dev0
    - certifi
    - semver >=2.10,<3.dev0
    - setuptools >=38.3
test:
  imports:
    - pyload
  commands:
    - set PYTHONIOENCODING=utf-8  # [win]
    - pip check
    - pyload --help
    - pyload --version
  requires:
    - pip

about:
  home: https://pyload.net
  summary: The free and open-source Download Manager written in pure Python
  license: AGPL-3.0-or-later
  license_file: LICENSE.md
  dev_url: https://github.com/pyload/pyload
  doc_url: https://github.com/pyload/pyload/wiki
  description: |
    *pyLoad* is a free and open source downloader for 1-click-hosting sites.
    It supports link decryption as well as all important container formats.
    Targeted for headless NASs it is designed to be extremely lightweight,
    fully customizable and remotely manageable via web interface.

extra:
  recipe-maintainers:
    - HeavyTony2
