{% set name = "pyload-ng" %}
{% set version = "0.5.0b3.dev93" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b93d0969f658a28d1404bf01d3ddcd249559ae43c2fdcbd797805b9cbcdb350e

build:
  entry_points:
    - pyload = pyload.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  build:
    - python {{ python_min }}
    - babel
    - jinja2
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=38.3
    - wheel
    - packaging
  run:
    - python >={{ python_min }},<3.14 #See mini-racer
    - pip
    - cheroot
    - flask
    - flask-babel
    - flask-caching >=1.9,<2.dev0
    - flask-compress >=1.8,<2.dev0
    - flask-session
    - flask-themes2 >=1.0,<2.dev0
    - bitmath >=1.3,<2.dev0
    - cryptography >=35.0.0
    - filetype >=1.0,<2.dev0
    - pycurl
    - certifi
    - semver >=2.10,<3.dev0
    - setuptools >=38.3
    - packaging
    - cryptography
    - pydantic >=2.10.6,<2.11.dev0
    - mini-racer #Isn't avalaible yet for 3.14 because gstuil isn't avalaible yet for 3.14

test:
  imports:
    - pyload
  commands:
    #- set PYTHONIOENCODING=utf-8  # [win]
    - pip check
    - pyload --help
    - pyload --version
  requires:
    - pip
    - msgspec =0.19 #metadata issues

about:
  home: https://pyload.net
  summary: The free and open-source Download Manager written in pure Python
  license: AGPL-3.0-or-later
  license_file: LICENSE.md
  dev_url: https://github.com/pyload/pyload
  doc_url: https://github.com/pyload/pyload/wiki
  description: |
    *pyLoad* is a free and open source downloader for 1-click-hosting sites.
    It supports link decryption as well as all important container formats.
    Targeted for headless NASs it is designed to be extremely lightweight,
    fully customizable and remotely manageable via web interface.

extra:
  recipe-maintainers:
    - HeavyTony2
