{% set name = "pyload-ng" %}
{% set version = "0.5.0b3.dev62" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyload-ng-{{ version }}.tar.gz
  sha256: c71d39807af53f885434dda7abe698b35aa0ea301143c0f3f7f492c91c0426c8

build:
  entry_points:
    - pyload = pyload.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - flask-session2
    - semver ~=2.10
    - bitmath >=1.3
    - Cheroot ~=8.4
    - cryptography >=36.0
    - filetype >=1.0
    - Flask ~=2.3.0
    - flask-babel =1.0
    - flask-caching >=1.9
    - flask-compress =1.8
    - flask-session >=0.3
    - flask-themes2 >=1.0
    - js2py >=0.7
    - pycurl >=7.43
    - python >=3.6
    - semver >=2.10
    - setuptools >=38.3
    - slixmpp
    - arm_pyart
    - beautifulsoup4
    - werkzeug
    - jinja2
    - Flask-Caching ~=1.9
    #- cython #could removed afterward not a direct dep

test:
  imports:
    - pyload
  commands:
    - pip check
    - pyload --help
    - pyload --version
  requires:
    - pip

about:
  home: https://pyload.net
  summary: The free and open-source Download Manager written in pure Python
  license: AGPL-3.0-or-later
  license_file: LICENSE.md
  dev_url: https://github.com/pyload/pyload
  doc_url: https://github.com/pyload/pyload/wiki

extra:
  recipe-maintainers:
    - HeavyTony2
