{% set name = "pyload-ng" %}
{% set version = "0.5.0b3.dev87" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2db8b16947ec59e53c595a59b122c998547f8552e10abd4346c21e15809cc450

build:
  skip: true  # [py>=312]
  #see PR and issues 58 & 57
  entry_points:
    - pyload = pyload.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 4

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools >=38.3
    - wheel
  run:
    - python
    - cheroot
    - flask
    - flask-babel >=1.0,<2.dev0
    - flask-caching >=1.9,<2.dev0
    - flask-compress >=1.8,<2.dev0
    - flask-session >=0.4.1,<0.5.dev0  #Should be for 37 or less according to grayskull, but not according to the tests
    - flask-themes2 >=1.0,<2.dev0
    - bitmath >=1.3,<2.dev0
    - cryptography >=35.0.0
    - filetype >=1.0,<2.dev0
    - js2py >=0.7,<1.dev0  # [py<312]
    - dukpy  # [py>=312]
    - pycurl >=7.43,<8.dev0
    - certifi
    - semver >=2.10,<3.dev0
    - setuptools >=38.3
    - pip <24 #Flask-Babel 1.0.0 issues

test:
  imports:
    - pyload
  commands:
    - set PYTHONIOENCODING=utf-8  # [win]
    - pip check
    - pyload --help
    - pyload --version 
  requires:
    - pip

about:
  home: https://pyload.net
  summary: The free and open-source Download Manager written in pure Python
  license: AGPL-3.0-or-later
  license_file: LICENSE.md
  dev_url: https://github.com/pyload/pyload
  doc_url: https://github.com/pyload/pyload/wiki
  description: |
    *pyLoad* is a free and open source downloader for 1-click-hosting sites.
    It supports link decryption as well as all important container formats.
    Targeted for headless NASs it is designed to be extremely lightweight,
    fully customizable and remotely manageable via web interface.

extra:
  recipe-maintainers:
    - HeavyTony2
