{% set name = "pyload-ng" %}
{% set version = "0.5.0b3.dev82" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 839a2a5d5f009f3c015e20b10316e85ec48fbe305324f543dc4d26c1d1062c70

build:
  entry_points:
    - pyload = pyload.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=38.3
    - wheel
  run:
    - flask-session2
    - semver ~=2.10
    - bitmath >=1.3,<2.dev0
    - cheroot >=8.4,<9.dev0
    - cryptography >=35.0.0
    - filetype >=1.0
    - flask ~=2.3
    - flask-babel >=1.0,<2.dev0
    - flask-caching >=1.9,<2.dev0
    - flask-compress >=1.8,<2.dev0
    - flask-session >=0.3
    - flask-themes2 >=1.0
    - js2py >=0.7
    - pycurl >=7.43,<8.dev0
    - python >=3.6
    - semver >=2.10,<3.dev0
    - setuptools >=38.3
    - slixmpp
    - arm_pyart
    - beautifulsoup4
    - werkzeug
    - jinja2
    - Flask-Caching ~=1.9

test:
  imports:
    - pyload
  commands:
    - pip check
    - pyload --help
    - pyload --version
  requires:
    - pip

about:
  home: https://pyload.net
  summary: The free and open-source Download Manager written in pure Python
  license: AGPL-3.0-or-later
  license_file: LICENSE.md
  dev_url: https://github.com/pyload/pyload
  doc_url: https://github.com/pyload/pyload/wiki
  description: |
    *pyLoad* is a free and open source downloader for 1-click-hosting sites.
    It supports link decryption as well as all important container formats.
    Targeted for headless NASs it is designed to be extremely lightweight,
    fully customizable and remotely manageable via web interface.

extra:
  recipe-maintainers:
    - HeavyTony2
