{% set name = "dukpy" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dukpy-{{ version }}.tar.gz
  sha256: 079fe2d65ac5e24df56806c6b4e1a26f92bb7f13dc764f4fb230a6746744c1ad

build:
  entry_points:
    - dukpy-install = dukpy.install:main
    - dukpy = dukpy.run:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - setuptools
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - dukpy
  commands:
    - pip check
    - dukpy-install --help
    - dukpy --help
  requires:
    - pip

about:
  home: https://github.com/amol-/dukpy
  summary: Simple JavaScript interpreter for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - HeavyTony2
