schema_version: 1

context:
  name: pyload-ng
  version: 0.5.0b3.dev95

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 1125702e6cc98204dae1a3cd579ea9fb8bb9015f92633693bb4d35d0fa381fdd

build:
  number: 2
  noarch: python
  #skip: ppc64le #mini-racer on ppc64le isn't avalaible for now
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  string: pymin${{ python_min }}_pyh${{ PKG_HASH }}_${{ PKG_BUILDNUM }}
  python:
    entry_points:
      - pyload = pyload.__main__:main

requirements:
  build:
    #- if: build_platform != target_platform
     # then: python
    #- if: build_platform != target_platform
    #  then: cross-python_${{ target_platform }}
    - babel
    - jinja2
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=38.3
    - wheel
    - packaging
  run:
    - python >=${{ python_min }},<${{ python_max }}
    - aia-chaser >=0.9.0
    - cheroot
    - flask
    - flask-babel
    - flask-caching >=1.9,<2.dev0
    - flask-compress >=1.8,<2.dev0
    - flask-session
    - flask-themes2 >=1.0,<2.dev0
    - flask-wtf
    - bitmath >=1.3,<2.dev0
    - cryptography >=35.0.0
    - defusedxml
    - filetype >=1.0,<2.dev0
    - mini-racer
    - packaging
    - pycurl
    - pydantic
    - certifi
    - semver >=2.10,<3.dev0
    - setuptools >=38.3

tests:
  - python:
      imports:
        - pyload
  - requirements:
      run:
        - pip
        - python {{ python_min }}.*
    script:
    #  - if: win
      #  then: set PYTHONIOENCODING=utf-8
      - pip check
      - pyload --help
      - pyload --version

about:
  summary: The free and open-source Download Manager written in pure Python
  license: AGPL-3.0-or-later
  license_file: LICENSE.md
  description: |
    *pyLoad* is a free and open source downloader for 1-click-hosting sites.
    It supports link decryption as well as all important container formats.
    Targeted for headless NASs it is designed to be extremely lightweight,
    fully customizable and remotely manageable via web interface.


  homepage: https://pyload.net
  repository: https://github.com/pyload/pyload
  documentation: https://github.com/pyload/pyload/wiki

extra:
  recipe-maintainers:
    - HeavyTony2
